repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-yaml
        args: ['--unsafe']
        # Évite que check-yaml ne tente d'analyser les faux YAML d'Unity
        exclude: ^unity/|.*\.asset$|.*\.unity$|.*\.meta$
    -   id: end-of-file-fixer
        # Empêche de modifier la fin des fichiers Unity (crucial pour TagManager)
        exclude: ^unity/|.*\.asset$|.*\.unity$|.*\.meta$
    -   id: trailing-whitespace
        # Empêche de supprimer des espaces dans les fichiers de config Unity
        exclude: ^unity/|.*\.asset$|.*\.unity$|.*\.meta$
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        exclude: ^unity/
