repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-yaml
        args: ['--unsafe']
    -   id: end-of-file-fixer
        exclude: ^unity/.*
    -   id: trailing-whitespace
        exclude: ^unity/.*
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
