site_name: Wawe game
site_description: Software project documentation
site_author: PuffinIT
repo_url: https://github.com/floorian651/wavr
repo_name: Wave

theme:
  name: material
  language: fr
  # logo: assets/logo.png
  # favicon: assets/favicon.png

  # Configuration du mode Sombre / Clair
  palette:
    # Mode Clair (par défaut)
    - scheme: default
      primary: indigo
      accent: purple
      toggle:
        icon: material/weather-night
        name: Passer au mode sombre

    # Mode Sombre
    - scheme: slate
      primary: indigo
      accent: lime
      toggle:
        icon: material/weather-sunny
        name: Passer au mode clair

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy

nav:
  - Accueil: index.md
  - PulseDash: game.md
  - Changelog: changelog.md
  - Guide utilisateur:
    - Premiers pas: user/getting-started.md
  - Développement:
    - Contribution: dev/CONTRIBUTING.md
    - Installation: dev/setup.md
    - API FastAPI: dev/api.md
    - Schéma des données: dev/data-schema.md
    - Architecture: dev/architecture.md
    - CI/CD & Pipeline:
      - Concepts CI/CD: dev/ci-cd.md
      - Pipeline détails: dev/pipeline.md

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - md_in_html
  - tables
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

  # Configuration Mermaid
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - awesome-pages

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css
